language: php
sudo: false
dist: trusty
php:
  - 8.0
  - 7.4
  - 7.3
  - nightly

env:
  - TRAVIS_NODE_VERSION="14"

matrix:
  fast_finish: true
  allow_failures:
    - php: nightly

cache:
  apt: true
  directories:
    - $HOME/.composer/cache
    - $HOME/.yarn-cache
    - vendor

before_install:
  - composer self-update

install:
  - composer install -o --prefer-dist --no-interaction

script:
  - composer test
